// This file was autogenerated by ../../../tools/closure/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../js/network/databuffer.js', ['network.ObjectBuffer'], []);
goog.addDependency('../../js/network/objectbuffer.js', ['network.ObjectBuffer'], []);
goog.addDependency('../../js/network/serializer.js', ['network.Serializer'], ['network.ObjectBuffer']);
goog.addDependency('../../js/network/snapshot.js', ['network.Snapshot'], ['network.ObjectBuffer']);
goog.addDependency('../../js/network/synchronizer.js', ['network.Synchronizer'], []);
