// This file was autogenerated by ../../../tools/closure/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../js/base/base.js', ['base', 'base.GeometryData', 'base.LightningType', 'base.Mesh', 'base.Model', 'base.ModelInstance'], ['base.Mat4', 'base.Vec3', 'goog.asserts']);
goog.addDependency('../../js/base/broker.js', ['base.Broker', 'base.FakeBroker', 'base.IBroker'], ['goog.array', 'goog.asserts']);
goog.addDependency('../../js/base/bsp.js', ['base.Bsp'], ['base', 'goog.asserts']);
goog.addDependency('../../js/base/iinputhandler.js', ['base.IInputHandler'], []);
goog.addDependency('../../js/base/irendererscene.js', ['base.IRendererScene'], []);
goog.addDependency('../../js/base/jobspool.js', ['base.JobsPool'], ['goog.asserts']);
goog.addDependency('../../js/base/map.js', ['base.Map'], ['base', 'base.Bsp']);
goog.addDependency('../../js/base/mat3.js', ['base.Mat3'], []);
goog.addDependency('../../js/base/mat4.js', ['base.Mat4'], ['base.Mat3', 'base.Vec3']);
goog.addDependency('../../js/base/material.js', ['base.Material', 'base.ShaderScript'], []);
goog.addDependency('../../js/base/pool.js', ['base.Pool'], ['goog.asserts']);
goog.addDependency('../../js/base/quat4.js', ['base.Quat4'], ['base.Mat3', 'base.Mat4', 'base.Vec3']);
goog.addDependency('../../js/base/vec3.js', ['base.Vec3', 'base.Vec4'], ['base.Pool']);
