// This file was autogenerated by closure/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../js/camera.js', ['camera'], ['gl-matrix', 'input']);
goog.addDependency('../../js/common.js', ['common'], []);
goog.addDependency('../../js/input.js', ['input'], []);
goog.addDependency('../../js/q3bsp_worker.js', ['q3bsp'], ['binaryFile', 'common', 'gl-matrix']);
goog.addDependency('../../js/q3glshader.js', ['q3GlShader'], ['common', 'gl-matrix']);
goog.addDependency('../../js/q3shader.js', ['q3ShaderLoader'], []);
goog.addDependency('../../js/renderer.js', ['renderer'], ['common', 'gl-matrix', 'goog.debug.Logger', 'goog.debug.Logger.Level', 'q3GlShader', 'q3ShaderLoader']);
goog.addDependency('../../js/resourceManager.js', ['resources'], ['goog.debug.Logger', 'zip.js']);
goog.addDependency('../../js/utilities/binary-file.js', ['binaryFile'], []);
goog.addDependency('../../js/utilities/gl-matrix.js', ['gl-matrix'], []);
goog.addDependency('../../js/utilities/zip.js/zip.js', ['zip.js'], []);
