// This file was autogenerated by closure/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../js/files/bsp.js', ['q3bsp'], ['binaryFile', 'common', 'gl-matrix']);
goog.addDependency('../../js/files/md3.js', ['resources.Md3'], ['binaryFile', 'goog.asserts']);
goog.addDependency('../../js/files/resourceManager.js', ['resources'], ['goog.debug.Logger', 'zip.js']);
goog.addDependency('../../js/files/shader.js', ['q3ShaderLoader'], []);
goog.addDependency('../../js/game/camera.js', ['camera'], ['gl-matrix', 'input']);
goog.addDependency('../../js/input.js', ['input'], []);
goog.addDependency('../../js/renderer/renderer.js', ['renderer'], ['common', 'gl-matrix', 'goog.debug.Logger', 'goog.debug.Logger.Level', 'q3GlShader', 'q3ShaderLoader']);
goog.addDependency('../../js/renderer/shader.js', ['q3GlShader'], ['common', 'gl-matrix']);
goog.addDependency('../../js/renderer/types.js', ['common'], []);
goog.addDependency('../../js/utilities/binary-file.js', ['binaryFile'], []);
goog.addDependency('../../js/utilities/gl-matrix.js', ['gl-matrix'], []);
goog.addDependency('../../js/utilities/zip.js/zip.js', ['zip.js'], []);
